language: python

dist: jammy

python:
  - '3.11'

# Install system dependencies
addons:
  apt:
    packages:
      - r-base  # Install R to support rpy2 and the R package

# Install dependencies
install:
  - pip install -r requirements.txt  # Install Python dependencies
  - pip install .
  - Rscript -e "if (!require('GeneralisedCovarianceMeasure')) install.packages('GeneralisedCovarianceMeasure', repos='http://cran.us.r-project.org')"  # Install the required R package

# Command to run tests
script:
  - pytest --maxfail=3 --disable-warnings
